apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketevolsvc-fe-deployment
  namespace: ticketevol-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketevolsvc-fe
  template:
    metadata:
      labels:
        app: ticketevolsvc-fe
    spec:
      containers:
        - name: ticketevolsvc-fe
          image: shiryuknight/ticketevolution-fe:v1.0.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
