apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketevolapp-be-deployment
  namespace: ticketevol-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketevolapp-be
  template:
    metadata:
      labels:
        app: ticketevolapp-be
    spec:
      # volumes:
      #   - name: ticketevolution-pg-postgresql-secret-volume
      #     secret:
      #       secretname: ticketevolution-pg-postgresql
      containers:
        - name: ticketevolapp-be
          image: shiryuknight/ticketevolution-be:v1.0.5
          imagePullPolicy: Always
          # volumeMounts:
          #   - mountPath: "/etc/ticketevol-pg-postgresql-secret-volume"
          #     readOnly: true
          #     name: ticketevolution-pg-postgresql-secret-volume
          ports:
            - containerPort: 3000
          env:
            - name: CONTAINER
              value: k8s
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ticketevolution-pg-postgresql
            - name: PGHOST
              value: ticketevolution-pg-postgresql-hl.ticketevol-be.svc.cluster.local
              # value: localhost
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: ticketevolution-pg-postgresql
            - name: PGUSERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: ticketevolution-pg-postgresql
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
