spring:
  profiles:
    active: local
  application:
    name: ticketevolution
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT}/${PGDATABASE}
    username: ${PGUSERNAME}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
server:
  servlet:
    contextPath: /api

