spring:
  profiles:
    active: local
  application:
    name: ticketevolution
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketevolutiondb
    username: ticketevolutionapp
    password: e3f4a48660ilm
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
